# Generated by Django 3.0.1 on 2019-12-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_name', models.CharField(max_length=16)),
                ('authors_surname', models.CharField(max_length=32)),
                ('authors_age', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.CharField(max_length=150)),
                ('post_text', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='Время публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author')),
            ],
        ),
    ]
